[2024-09-13T16:28:24.485+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:28:20.127425+00:00 [queued]>
[2024-09-13T16:28:24.490+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:28:20.127425+00:00 [queued]>
[2024-09-13T16:28:24.491+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:28:24.491+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-13T16:28:24.491+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:28:24.584+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2024-09-13 16:28:20.127425+00:00
[2024-09-13T16:28:24.587+0000] {standard_task_runner.py:55} INFO - Started process 916 to run task
[2024-09-13T16:28:24.589+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'load_task', 'manual__2024-09-13T16:28:20.127425+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpe50j1gfg']
[2024-09-13T16:28:24.591+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask load_task
[2024-09-13T16:28:24.605+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-13T16:28:24.650+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:28:20.127425+00:00 [running]> on host 2656b950921d
[2024-09-13T16:28:24.786+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pipeline_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-13T16:28:20.127425+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-13T16:28:20.127425+00:00
[2024-09-13T16:28:24.787+0000] {logging_mixin.py:137} INFO - Failed to load data into PostgreSQL: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
[2024-09-13T16:28:24.787+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/tasks/loader.py", line 8, in loader
    parsed_data = json.loads(parsed_data_json)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
[2024-09-13T16:28:24.795+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pipeline_dag, task_id=load_task, execution_date=20240913T162820, start_date=20240913T162824, end_date=20240913T162824
[2024-09-13T16:28:24.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task load_task (Expecting property name enclosed in double quotes: line 1 column 3 (char 2); 916)
[2024-09-13T16:28:24.842+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-13T16:28:24.859+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
